name: Auto Dev Builds 
 
on: [push, pull_request]
      
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delete existing assets from 'dev' release
      uses: actions/github-script@v6
      id: delete-assets
      with:
        script: |
          const tag = 'dev';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Get the release by tag
          const release = await github.rest.repos.getReleaseByTag({
            owner,
            repo,
            tag
          });

          // Delete each asset in the release
          const assets = release.data.assets;
          for (const asset of assets) {
            await github.rest.repos.deleteReleaseAsset({
              owner,
              repo,
              asset_id: asset.id
            });
          }


    - name: Get full repository history
      run: |
        git remote add freedomscoops https://github.com/freedomscoops/freedomscoops-dev.git
        git fetch --all
  
    - name: Install Prerequisites
      run: |
        sudo apt update
        sudo apt install python3-pil asciidoc unzip zip ruby dos2unix
        sudo gem install asciidoctor-pdf --pre
        
    - name: Install Deutex
      run: |
        git clone https://github.com/Doom-Utils/deutex.git
        cd deutex
        git checkout v5.2.1
        sudo apt install libpng-dev
        ./bootstrap
        ./configure
        make
        sudo make install
 
    - name: Build
      run: |
         curl -o FDCREDITS https://raw.githubusercontent.com/freedoom/freedoom/master/CREDITS
         make dist

    - name: Copy ZIP files from wads folder
      run: |
          mkdir -p release
          cp wads/*.zip release
          ls release 

    - name: Get current date
      id: date
      run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: "release/*.zip "  # Specify the path to the .zip files directly
        #token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: dev
        name: Freedom Scoops Auto Builds ${{ steps.date.outputs.date }} #${{ github.run_number }}
        prerelease: true
        body_path: .github/notes/dev.txt

